/* 1. CREATE DATABASE */

DROP DATABASE IF EXISTS ecommerce_store;

-- Create Database using utf8mb4 to support full Unicode (all special characters)
-- Collation defines how text is compared and sorted (utf8mb4_unicode_ci = Unicode-aware, case-insensitive)
CREATE DATABASE ecommerce_store
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE ecommerce_store;

/* 2. CREATE TABLES */
-- 1. CATEGORIES TABLE
CREATE TABLE CATEGORIES (
    CATEGORY_ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    CATEGORY_NAME VARCHAR(20) NOT NULL,

    CONSTRAINT pk_category PRIMARY KEY (CATEGORY_ID),
    CONSTRAINT uq_category_name UNIQUE (CATEGORY_NAME)
) ENGINE=InnoDB;

-- 2. PRODUCTS TABLE
CREATE TABLE PRODUCTS (
    PRODUCT_ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    PRODUCT_CATEGORY_ID INT UNSIGNED NOT NULL,
    PRODUCT_EXTERNAL_ID VARCHAR(100) NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    PRODUCT_DESCRIPTION TEXT,
    PRODUCT_BRAND VARCHAR(255),
    PRODUCT_IN_STOCK TINYINT(1) NOT NULL,

    CONSTRAINT pk_product PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT uq_product_external_id UNIQUE (PRODUCT_EXTERNAL_ID),

    CONSTRAINT fk_products_category FOREIGN KEY (PRODUCT_CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID)
        ON DELETE RESTRICT
) ENGINE=InnoDB;

-- 3. CURRENCIES TABLE
CREATE TABLE CURRENCIES (
    CURRENCY_ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    CURRENCY_LABEL VARCHAR(10) NOT NULL,
    CURRENCY_SYMBOL VARCHAR(5) NOT NULL,

    CONSTRAINT pk_currency PRIMARY KEY (CURRENCY_ID),
    CONSTRAINT uq_currency_label UNIQUE (CURRENCY_LABEL)
) ENGINE=InnoDB;

-- 4. PRICES TABLE
CREATE TABLE PRICES (
    PRICE_ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    PRICE_PRODUCT_ID INT UNSIGNED NOT NULL,
    PRICE_CURRENCY_ID INT UNSIGNED NOT NULL,
    PRICE_AMOUNT DECIMAL(10,2) NOT NULL,

    CONSTRAINT pk_price PRIMARY KEY (PRICE_ID),
    CONSTRAINT uq_price_product_currency UNIQUE (PRICE_PRODUCT_ID, PRICE_CURRENCY_ID),

    CONSTRAINT fk_prices_product FOREIGN KEY (PRICE_PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_prices_currency FOREIGN KEY (PRICE_CURRENCY_ID) REFERENCES CURRENCIES(CURRENCY_ID)
        ON DELETE RESTRICT
) ENGINE=InnoDB;

-- 5. IMAGES TABLE
CREATE TABLE IMAGES (
    IMAGE_ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    IMAGE_PRODUCT_ID INT UNSIGNED NOT NULL,
    IMAGE_URL VARCHAR(255) NOT NULL,

    CONSTRAINT pk_image PRIMARY KEY (IMAGE_ID),
    CONSTRAINT uq_image_product_url UNIQUE (IMAGE_PRODUCT_ID, IMAGE_URL),

    CONSTRAINT fk_images_product FOREIGN KEY (IMAGE_PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB;

-- 6. ATTRIBUTES TABLE
CREATE TABLE ATTRIBUTES (
    ATTRIBUTE_ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    ATTRIBUTE_EXTERNAL_ID VARCHAR(100) NOT NULL,
    ATTRIBUTE_NAME VARCHAR(100) NOT NULL,
    ATTRIBUTE_TYPE VARCHAR(20) NOT NULL,

    CONSTRAINT pk_attribute PRIMARY KEY (ATTRIBUTE_ID),
    CONSTRAINT uq_attribute_external UNIQUE (ATTRIBUTE_EXTERNAL_ID)
) ENGINE=InnoDB;

-- 7. ATTRIBUTES_ITEMS TABLE
CREATE TABLE ATTRIBUTE_ITEMS (
    ATTRIBUTE_ITEM_ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    ATTRIBUTE_ITEM_ATTRIBUTE_ID INT UNSIGNED NOT NULL,
    ATTRIBUTE_ITEM_EXTERNAL_ID VARCHAR(100) NOT NULL,
    ATTRIBUTE_ITEM_DISPLAY_VALUE VARCHAR(100) NOT NULL,
    ATTRIBUTE_ITEM_VALUE VARCHAR(100) NOT NULL,

    CONSTRAINT pk_item PRIMARY KEY (ATTRIBUTE_ITEM_ID),
    CONSTRAINT uq_item_attribute_external UNIQUE (ATTRIBUTE_ITEM_ATTRIBUTE_ID, ATTRIBUTE_ITEM_EXTERNAL_ID),

    CONSTRAINT fk_items_attribute FOREIGN KEY (ATTRIBUTE_ITEM_ATTRIBUTE_ID) REFERENCES ATTRIBUTES(ATTRIBUTE_ID)
        ON DELETE RESTRICT
) ENGINE=InnoDB;

-- 8. PRODUCT_ATTRIBUTE_ITEMS TABLE
CREATE TABLE PRODUCT_ATTRIBUTE_ITEMS (
    PRODUCT_ATTRIBUTE_ITEM_ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    PRODUCT_ATTRIBUTE_ITEM_ATTRIBUTE_ITEM_ID INT UNSIGNED NOT NULL,
    PRODUCT_ATTRIBUTE_ITEM_PRODUCT_ID INT UNSIGNED NOT NULL,

    CONSTRAINT pk_product_attribute_item PRIMARY KEY (PRODUCT_ATTRIBUTE_ITEM_ID),
    CONSTRAINT uq_product_attribute_item UNIQUE
        (PRODUCT_ATTRIBUTE_ITEM_ATTRIBUTE_ITEM_ID, PRODUCT_ATTRIBUTE_ITEM_PRODUCT_ID),

    CONSTRAINT fk_product_attribute_items_attribute_item FOREIGN KEY (PRODUCT_ATTRIBUTE_ITEM_ATTRIBUTE_ITEM_ID)
        REFERENCES ATTRIBUTE_ITEMS(ATTRIBUTE_ITEM_ID) ON DELETE CASCADE,

    CONSTRAINT fk_product_attribute_items_product FOREIGN KEY (PRODUCT_ATTRIBUTE_ITEM_PRODUCT_ID)
        REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE
) ENGINE=InnoDB;

-- 9. ORDERS TABLE
CREATE TABLE ORDERS (
    ORDER_ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    ORDER_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ORDER_TOTAL_AMOUNT DECIMAL(10,2) NOT NULL,

    CONSTRAINT pk_order PRIMARY KEY (ORDER_ID)
) ENGINE=InnoDB;

-- 10. ORDER_ITEMS TABLE
CREATE TABLE ORDER_ITEMS (
    ORDER_ITEM_ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    ORDER_ITEM_ORDER_ID INT UNSIGNED NOT NULL,
    ORDER_ITEM_PRODUCT_ID INT UNSIGNED NOT NULL,
    ORDER_ITEM_QUANTITY INT UNSIGNED NOT NULL,
    ORDER_ITEM_PRICE DECIMAL(10,2) NOT NULL,

    CONSTRAINT pk_order_item PRIMARY KEY (ORDER_ITEM_ID),

    CONSTRAINT fk_order_items_order FOREIGN KEY (ORDER_ITEM_ORDER_ID) REFERENCES ORDERS(ORDER_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_order_items_product FOREIGN KEY (ORDER_ITEM_PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
        ON DELETE RESTRICT
) ENGINE=InnoDB;

-- 11. ORDER_ITEM_ATTRIBUTES TABLE
CREATE TABLE ORDER_ITEM_ATTRIBUTES (
    ORDER_ITEM_ATTRIBUTE_ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    ORDER_ITEM_ATTRIBUTE_ORDER_ITEM_ID INT UNSIGNED NOT NULL,
    ORDER_ITEM_ATTRIBUTE_ATTRIBUTE_ITEM_ID INT UNSIGNED NOT NULL,

    CONSTRAINT pk_order_item_attribute PRIMARY KEY (ORDER_ITEM_ATTRIBUTE_ID),
    CONSTRAINT uq_order_item_attribute
        UNIQUE (ORDER_ITEM_ATTRIBUTE_ORDER_ITEM_ID, ORDER_ITEM_ATTRIBUTE_ATTRIBUTE_ITEM_ID),

    CONSTRAINT fk_order_item_attributes_order_item FOREIGN KEY (ORDER_ITEM_ATTRIBUTE_ORDER_ITEM_ID)
        REFERENCES ORDER_ITEMS(ORDER_ITEM_ID) ON DELETE CASCADE,

    CONSTRAINT fk_order_item_attributes_attribute_item FOREIGN KEY (ORDER_ITEM_ATTRIBUTE_ATTRIBUTE_ITEM_ID)
        REFERENCES ATTRIBUTE_ITEMS(ATTRIBUTE_ITEM_ID) ON DELETE RESTRICT
) ENGINE=InnoDB;
