/* 1. CREATE DATABASE */

DROP DATABASE IF EXISTS ecommerce_store;

-- Create database using utf8mb4 to support full Unicode (all special characters)
-- Collation defines how text is compared and sorted (utf8mb4_unicode_ci = Unicode-aware, case-insensitive)
CREATE DATABASE ecommerce_store
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE ecommerce_store;

/* 2. CREATE TABLES */
-- CATEGORIES TABLE
CREATE TABLE CATEGORIES (
    CATEGORY_ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    CATEGORY_NAME VARCHAR(20) NOT NULL,

    CONSTRAINT pk_category PRIMARY KEY (CATEGORY_ID),
    CONSTRAINT uq_category_name UNIQUE (CATEGORY_NAME)
) ENGINE=InnoDB;

-- PRODUCTS TABLE
CREATE TABLE PRODUCTS (
    PRODUCT_ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    PRODUCT_CATEGORY_ID INT UNSIGNED NOT NULL,
    PRODUCT_EXTERNAL_ID VARCHAR(100) NOT NULL,
    PRODUCT_NAME VARCHAR(255) NOT NULL,
    PRODUCT_DESCRIPTION TEXT,
    PRODUCT_BRAND VARCHAR(255),
    PRODUCT_IN_STOCK TINYINT(1) NOT NULL,

    CONSTRAINT pk_product PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT uq_product_external_id UNIQUE (PRODUCT_EXTERNAL_ID),

    CONSTRAINT fk_products_category FOREIGN KEY (PRODUCT_CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID)
        ON DELETE RESTRICT
) ENGINE=InnoDB;

-- CURRENCIES TABLE
CREATE TABLE CURRENCIES (
    CURRENCY_ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    CURRENCY_LABEL VARCHAR(10) NOT NULL,
    CURRENCY_SYMBOL VARCHAR(5) NOT NULL,

    CONSTRAINT pk_currency PRIMARY KEY (CURRENCY_ID),
    CONSTRAINT uq_currency_label UNIQUE (CURRENCY_LABEL)
) ENGINE=InnoDB;

-- PRICES TABLE
CREATE TABLE PRICES (
    PRICE_ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    PRICE_PRODUCT_ID INT UNSIGNED NOT NULL,
    PRICE_CURRENCY_ID INT UNSIGNED NOT NULL,
    PRICE_AMOUNT DECIMAL(10,2) NOT NULL,

    CONSTRAINT pk_price PRIMARY KEY (PRICE_ID),
    CONSTRAINT uq_price_product_currency UNIQUE (PRICE_PRODUCT_ID, PRICE_CURRENCY_ID),

    CONSTRAINT fk_prices_product FOREIGN KEY (PRICE_PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
        ON DELETE CASCADE,

    CONSTRAINT fk_prices_currency FOREIGN KEY (PRICE_CURRENCY_ID) REFERENCES CURRENCIES(CURRENCY_ID)
        ON DELETE RESTRICT
) ENGINE=InnoDB;

-- IMAGES TABLE
CREATE TABLE IMAGES (
    IMAGE_ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    IMAGE_PRODUCT_ID INT UNSIGNED NOT NULL,
    IMAGE_URL VARCHAR(255) NOT NULL,

    CONSTRAINT pk_image PRIMARY KEY (IMAGE_ID),
    CONSTRAINT uq_image_product_url UNIQUE (IMAGE_PRODUCT_ID, IMAGE_URL),

    CONSTRAINT fk_images_product FOREIGN KEY (IMAGE_PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB;

-- ATTRIBUTES TABLE
CREATE TABLE ATTRIBUTES (
    ATTRIBUTE_ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    ATTRIBUTE_PRODUCT_ID INT UNSIGNED NOT NULL,
    ATTRIBUTE_EXTERNAL_ID VARCHAR(100) NOT NULL,
    ATTRIBUTE_NAME VARCHAR(100) NOT NULL,
    ATTRIBUTE_TYPE VARCHAR(20) NOT NULL,

    CONSTRAINT pk_attribute PRIMARY KEY (ATTRIBUTE_ID),
    CONSTRAINT uq_attribute_product_external UNIQUE (ATTRIBUTE_PRODUCT_ID, ATTRIBUTE_EXTERNAL_ID),

    CONSTRAINT fk_attributes_product FOREIGN KEY (ATTRIBUTE_PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB;

-- ITEMS TABLE
CREATE TABLE ITEMS (
    ITEM_ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    ITEM_ATTRIBUTE_ID INT UNSIGNED NOT NULL,
    ITEM_EXTERNAL_ID VARCHAR(100) NOT NULL,
    ITEM_DISPLAY_VALUE VARCHAR(100) NOT NULL,
    ITEM_VALUE VARCHAR(100) NOT NULL,

    CONSTRAINT pk_item PRIMARY KEY (ITEM_ID),
    CONSTRAINT uq_item_attribute_external UNIQUE (ITEM_ATTRIBUTE_ID, ITEM_EXTERNAL_ID),

    CONSTRAINT fk_items_attribute FOREIGN KEY (ITEM_ATTRIBUTE_ID) REFERENCES ATTRIBUTES(ATTRIBUTE_ID)
        ON DELETE CASCADE
) ENGINE=InnoDB;
